server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /api/service_payments

spring:
  application:
    name: service_payments
  config:
    import:
      - classpath:shared-datasource.yaml
      - classpath:shared-security.yaml

springdoc:
  api:
    title: Store
    description: Store Description
    version: 1
